//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorClient.SensorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SensorServiceReference.ISensorService")]
    public interface ISensorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISensorService/SubmitReading", ReplyAction="http://tempuri.org/ISensorService/SubmitReadingResponse")]
        void SubmitReading(int sensorId, double value, System.DateTime timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISensorService/SubmitReading", ReplyAction="http://tempuri.org/ISensorService/SubmitReadingResponse")]
        System.Threading.Tasks.Task SubmitReadingAsync(int sensorId, double value, System.DateTime timestamp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISensorServiceChannel : SensorClient.SensorServiceReference.ISensorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SensorServiceClient : System.ServiceModel.ClientBase<SensorClient.SensorServiceReference.ISensorService>, SensorClient.SensorServiceReference.ISensorService {
        
        public SensorServiceClient() {
        }
        
        public SensorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SensorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SensorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SensorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SubmitReading(int sensorId, double value, System.DateTime timestamp) {
            base.Channel.SubmitReading(sensorId, value, timestamp);
        }
        
        public System.Threading.Tasks.Task SubmitReadingAsync(int sensorId, double value, System.DateTime timestamp) {
            return base.Channel.SubmitReadingAsync(sensorId, value, timestamp);
        }
    }
}
